name: Dock
run-name: Dockings=
on: [push]
jobs:
  Docker_container_run:
    runs-on: ubuntu-latest
    steps:
      - name: apt-get docker.io
        run: |
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y

      - name: check
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build docker
        run: docker build -t builder .

      - name: Start a container
        run: docker run --name test -t builder ls

      - name: Copy log
        run: docker cp test:/repo/log.txt ./log.txt

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: /home/runner/work/lab_08/lab_08/log.txt

